// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quiz de Dependência Emocional no Amor | Teste Gratuito e Científico",
  description: "Descubra se você tem dependência emocional no amor com nosso quiz científico gratuito. Mais de 50.000 pessoas já fizeram o teste. Resultado personalizado em 5 minutos.",
  keywords: [
    "dependência emocional",
    "dependência emocional no amor",
    "quiz dependência emocional",
    "teste dependência emocional",
    "relacionamento tóxico",
    "autoestima no relacionamento",
    "ciúme excessivo",
    "medo do abandono",
    "apego ansioso",
    "independência emocional"
  ],
  authors: [{ name: "Quiz Dependência Emocional" }],
  creator: "Quiz Dependência Emocional",
  publisher: "Quiz Dependência Emocional",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("https://quiz-dependencia-emocional.com"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Quiz de Dependência Emocional no Amor | Teste Gratuito",
    description: "Descubra se você tem dependência emocional no amor. Quiz científico gratuito com resultado personalizado em 5 minutos.",
    url: "https://quiz-dependencia-emocional.com",
    siteName: "Quiz Dependência Emocional",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Quiz de Dependência Emocional no Amor",
      },
    ],
    locale: "pt_BR",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Quiz de Dependência Emocional no Amor | Teste Gratuito",
    description: "Descubra se você tem dependência emocional no amor. Quiz científico gratuito com resultado personalizado.",
    images: ["/og-image.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "your-google-verification-code",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="canonical" href="https://quiz-dependencia-emocional.com" />
        <meta name="theme-color" content="#ec4899" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Quiz Dependência Emocional" />
        
        {/* Schema.org structured data */}
        <Script
          id="structured-data"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebApplication",
              "name": "Quiz de Dependência Emocional no Amor",
              "description": "Quiz científico gratuito para identificar padrões de dependência emocional em relacionamentos amorosos",
              "url": "https://quiz-dependencia-emocional.com",
              "applicationCategory": "HealthApplication",
              "operatingSystem": "Web",
              "offers": {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "BRL"
              },
              "author": {
                "@type": "Organization",
                "name": "Quiz Dependência Emocional"
              },
              "aggregateRating": {
                "@type": "AggregateRating",
                "ratingValue": "4.9",
                "ratingCount": "50000"
              }
            })
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}